// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package syncer

import (
	"context"
	"github.com/Orfeo42/claude-memory-sync/internal/manifest"
	"sync"
)

// Ensure, that MockHTTPClient does implement HTTPClient.
// If this is not the case, regenerate this file with moq.
var _ HTTPClient = &MockHTTPClient{}

// MockHTTPClient is a mock implementation of HTTPClient.
//
//	func TestSomethingThatUsesHTTPClient(t *testing.T) {
//
//		// make and configure a mocked HTTPClient
//		mockedHTTPClient := &MockHTTPClient{
//			CanonicalTreeFunc: func(ctx context.Context) (manifest.Manifest, error) {
//				panic("mock out the CanonicalTree method")
//			},
//			ClientTreeFunc: func(ctx context.Context) (manifest.Manifest, error) {
//				panic("mock out the ClientTree method")
//			},
//			DeleteClientFileFunc: func(ctx context.Context, path string) error {
//				panic("mock out the DeleteClientFile method")
//			},
//			GetCanonicalFileFunc: func(ctx context.Context, path string) ([]byte, error) {
//				panic("mock out the GetCanonicalFile method")
//			},
//			PutClientFileFunc: func(ctx context.Context, path string, content []byte) error {
//				panic("mock out the PutClientFile method")
//			},
//		}
//
//		// use mockedHTTPClient in code that requires HTTPClient
//		// and then make assertions.
//
//	}
type MockHTTPClient struct {
	// CanonicalTreeFunc mocks the CanonicalTree method.
	CanonicalTreeFunc func(ctx context.Context) (manifest.Manifest, error)

	// ClientTreeFunc mocks the ClientTree method.
	ClientTreeFunc func(ctx context.Context) (manifest.Manifest, error)

	// DeleteClientFileFunc mocks the DeleteClientFile method.
	DeleteClientFileFunc func(ctx context.Context, path string) error

	// GetCanonicalFileFunc mocks the GetCanonicalFile method.
	GetCanonicalFileFunc func(ctx context.Context, path string) ([]byte, error)

	// PutClientFileFunc mocks the PutClientFile method.
	PutClientFileFunc func(ctx context.Context, path string, content []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// CanonicalTree holds details about calls to the CanonicalTree method.
		CanonicalTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ClientTree holds details about calls to the ClientTree method.
		ClientTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteClientFile holds details about calls to the DeleteClientFile method.
		DeleteClientFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// GetCanonicalFile holds details about calls to the GetCanonicalFile method.
		GetCanonicalFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// PutClientFile holds details about calls to the PutClientFile method.
		PutClientFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Content is the content argument value.
			Content []byte
		}
	}
	lockCanonicalTree    sync.RWMutex
	lockClientTree       sync.RWMutex
	lockDeleteClientFile sync.RWMutex
	lockGetCanonicalFile sync.RWMutex
	lockPutClientFile    sync.RWMutex
}

// CanonicalTree calls CanonicalTreeFunc.
func (mock *MockHTTPClient) CanonicalTree(ctx context.Context) (manifest.Manifest, error) {
	if mock.CanonicalTreeFunc == nil {
		panic("MockHTTPClient.CanonicalTreeFunc: method is nil but HTTPClient.CanonicalTree was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCanonicalTree.Lock()
	mock.calls.CanonicalTree = append(mock.calls.CanonicalTree, callInfo)
	mock.lockCanonicalTree.Unlock()
	return mock.CanonicalTreeFunc(ctx)
}

// CanonicalTreeCalls gets all the calls that were made to CanonicalTree.
// Check the length with:
//
//	len(mockedHTTPClient.CanonicalTreeCalls())
func (mock *MockHTTPClient) CanonicalTreeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCanonicalTree.RLock()
	calls = mock.calls.CanonicalTree
	mock.lockCanonicalTree.RUnlock()
	return calls
}

// ClientTree calls ClientTreeFunc.
func (mock *MockHTTPClient) ClientTree(ctx context.Context) (manifest.Manifest, error) {
	if mock.ClientTreeFunc == nil {
		panic("MockHTTPClient.ClientTreeFunc: method is nil but HTTPClient.ClientTree was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClientTree.Lock()
	mock.calls.ClientTree = append(mock.calls.ClientTree, callInfo)
	mock.lockClientTree.Unlock()
	return mock.ClientTreeFunc(ctx)
}

// ClientTreeCalls gets all the calls that were made to ClientTree.
// Check the length with:
//
//	len(mockedHTTPClient.ClientTreeCalls())
func (mock *MockHTTPClient) ClientTreeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClientTree.RLock()
	calls = mock.calls.ClientTree
	mock.lockClientTree.RUnlock()
	return calls
}

// DeleteClientFile calls DeleteClientFileFunc.
func (mock *MockHTTPClient) DeleteClientFile(ctx context.Context, path string) error {
	if mock.DeleteClientFileFunc == nil {
		panic("MockHTTPClient.DeleteClientFileFunc: method is nil but HTTPClient.DeleteClientFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockDeleteClientFile.Lock()
	mock.calls.DeleteClientFile = append(mock.calls.DeleteClientFile, callInfo)
	mock.lockDeleteClientFile.Unlock()
	return mock.DeleteClientFileFunc(ctx, path)
}

// DeleteClientFileCalls gets all the calls that were made to DeleteClientFile.
// Check the length with:
//
//	len(mockedHTTPClient.DeleteClientFileCalls())
func (mock *MockHTTPClient) DeleteClientFileCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockDeleteClientFile.RLock()
	calls = mock.calls.DeleteClientFile
	mock.lockDeleteClientFile.RUnlock()
	return calls
}

// GetCanonicalFile calls GetCanonicalFileFunc.
func (mock *MockHTTPClient) GetCanonicalFile(ctx context.Context, path string) ([]byte, error) {
	if mock.GetCanonicalFileFunc == nil {
		panic("MockHTTPClient.GetCanonicalFileFunc: method is nil but HTTPClient.GetCanonicalFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockGetCanonicalFile.Lock()
	mock.calls.GetCanonicalFile = append(mock.calls.GetCanonicalFile, callInfo)
	mock.lockGetCanonicalFile.Unlock()
	return mock.GetCanonicalFileFunc(ctx, path)
}

// GetCanonicalFileCalls gets all the calls that were made to GetCanonicalFile.
// Check the length with:
//
//	len(mockedHTTPClient.GetCanonicalFileCalls())
func (mock *MockHTTPClient) GetCanonicalFileCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockGetCanonicalFile.RLock()
	calls = mock.calls.GetCanonicalFile
	mock.lockGetCanonicalFile.RUnlock()
	return calls
}

// PutClientFile calls PutClientFileFunc.
func (mock *MockHTTPClient) PutClientFile(ctx context.Context, path string, content []byte) error {
	if mock.PutClientFileFunc == nil {
		panic("MockHTTPClient.PutClientFileFunc: method is nil but HTTPClient.PutClientFile was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Content []byte
	}{
		Ctx:     ctx,
		Path:    path,
		Content: content,
	}
	mock.lockPutClientFile.Lock()
	mock.calls.PutClientFile = append(mock.calls.PutClientFile, callInfo)
	mock.lockPutClientFile.Unlock()
	return mock.PutClientFileFunc(ctx, path, content)
}

// PutClientFileCalls gets all the calls that were made to PutClientFile.
// Check the length with:
//
//	len(mockedHTTPClient.PutClientFileCalls())
func (mock *MockHTTPClient) PutClientFileCalls() []struct {
	Ctx     context.Context
	Path    string
	Content []byte
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Content []byte
	}
	mock.lockPutClientFile.RLock()
	calls = mock.calls.PutClientFile
	mock.lockPutClientFile.RUnlock()
	return calls
}
