// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package store

import (
	"claude-memory-sync/internal/manifest"
	"context"
	"sync"
)

// Ensure, that MockStore does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &MockStore{}

// MockStore is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &MockStore{
//			DeleteFunc: func(ctx context.Context, namespace string, path string, clientID string) error {
//				panic("mock out the Delete method")
//			},
//			ReadFunc: func(ctx context.Context, namespace string, path string) ([]byte, error) {
//				panic("mock out the Read method")
//			},
//			TreeFunc: func(ctx context.Context, namespace string) (manifest.Manifest, error) {
//				panic("mock out the Tree method")
//			},
//			WriteFunc: func(ctx context.Context, namespace string, path string, content []byte, clientID string) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type MockStore struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, namespace string, path string, clientID string) error

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, namespace string, path string) ([]byte, error)

	// TreeFunc mocks the Tree method.
	TreeFunc func(ctx context.Context, namespace string) (manifest.Manifest, error)

	// WriteFunc mocks the Write method.
	WriteFunc func(ctx context.Context, namespace string, path string, content []byte, clientID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Path is the path argument value.
			Path string
			// ClientID is the clientID argument value.
			ClientID string
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Path is the path argument value.
			Path string
		}
		// Tree holds details about calls to the Tree method.
		Tree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Path is the path argument value.
			Path string
			// Content is the content argument value.
			Content []byte
			// ClientID is the clientID argument value.
			ClientID string
		}
	}
	lockDelete sync.RWMutex
	lockRead   sync.RWMutex
	lockTree   sync.RWMutex
	lockWrite  sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *MockStore) Delete(ctx context.Context, namespace string, path string, clientID string) error {
	if mock.DeleteFunc == nil {
		panic("MockStore.DeleteFunc: method is nil but Store.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Path      string
		ClientID  string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Path:      path,
		ClientID:  clientID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, namespace, path, clientID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStore.DeleteCalls())
func (mock *MockStore) DeleteCalls() []struct {
	Ctx       context.Context
	Namespace string
	Path      string
	ClientID  string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Path      string
		ClientID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *MockStore) Read(ctx context.Context, namespace string, path string) ([]byte, error) {
	if mock.ReadFunc == nil {
		panic("MockStore.ReadFunc: method is nil but Store.Read was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Path      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Path:      path,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, namespace, path)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedStore.ReadCalls())
func (mock *MockStore) ReadCalls() []struct {
	Ctx       context.Context
	Namespace string
	Path      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Path      string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Tree calls TreeFunc.
func (mock *MockStore) Tree(ctx context.Context, namespace string) (manifest.Manifest, error) {
	if mock.TreeFunc == nil {
		panic("MockStore.TreeFunc: method is nil but Store.Tree was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
	}{
		Ctx:       ctx,
		Namespace: namespace,
	}
	mock.lockTree.Lock()
	mock.calls.Tree = append(mock.calls.Tree, callInfo)
	mock.lockTree.Unlock()
	return mock.TreeFunc(ctx, namespace)
}

// TreeCalls gets all the calls that were made to Tree.
// Check the length with:
//
//	len(mockedStore.TreeCalls())
func (mock *MockStore) TreeCalls() []struct {
	Ctx       context.Context
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
	}
	mock.lockTree.RLock()
	calls = mock.calls.Tree
	mock.lockTree.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *MockStore) Write(ctx context.Context, namespace string, path string, content []byte, clientID string) error {
	if mock.WriteFunc == nil {
		panic("MockStore.WriteFunc: method is nil but Store.Write was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Path      string
		Content   []byte
		ClientID  string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Path:      path,
		Content:   content,
		ClientID:  clientID,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(ctx, namespace, path, content, clientID)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedStore.WriteCalls())
func (mock *MockStore) WriteCalls() []struct {
	Ctx       context.Context
	Namespace string
	Path      string
	Content   []byte
	ClientID  string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Path      string
		Content   []byte
		ClientID  string
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
